---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0  # Package updates are disabled for now.
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0  # Package updates are disabled for now.
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: "scope"
